In [600]:
# Numpy Basics-

In [601]:
#                Why do we need NumPy ? 
# A question arises that why do we need NumPy when python lists are already there. 
# The answer to it is we cannot perform operations on all the elements of two list directly. 
# For example we cannot multiply two lists directly we will have to do it element wise.
# This is where the role of NumPy comes into play.

In [602]:
# Array Creation-
# Array creation using numpy methods -
import numpy as np
arr1 = np.array([1,8,11])
arr1

array([ 1,  8, 11])

In [603]:
arr2 = np.array([[1,5,88],[1,4,99]])
arr2

array([[ 1,  5, 88],
       [ 1,  4, 99]])

In [604]:
arr3 = np.array((1,2,3,8))
arr3

array([1, 2, 3, 8])

In [605]:
type(arr3)

numpy.ndarray

In [606]:
arr4 = np.ones(3)
arr4

array([ 1.,  1.,  1.])

In [607]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [608]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [609]:
arr5 = np.array([[1,5,9],[4,88,10]],dtype=int)
arr5


array([[ 1,  5,  9],
       [ 4, 88, 10]])

In [610]:
# defining datatype-
np.array([[1,8,9],[5,8,4]],dtype = float)

array([[ 1.,  8.,  9.],
       [ 5.,  8.,  4.]])

In [611]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [612]:
# returns identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [613]:
# returns evenly spaced values within a given interval. step size is specified
np.arange(1,16,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [614]:
# returns evenly spaced values within a given interval. num no. of elements are returned.
np.linspace(1,16,4)

array([  1.,   6.,  11.,  16.])

In [615]:
np.arange(1,16,4)

array([ 1,  5,  9, 13])

In [616]:
# 2x4 array of all values of 8
np.full((2,4),8,dtype = int)

array([[8, 8, 8, 8],
       [8, 8, 8, 8]])

In [617]:
#4x5 array of random floats between 0-1
np.random.rand(2,3)

array([[ 0.95481916,  0.85522746,  0.18086976],
       [ 0.93613043,  0.44384845,  0.68484131]])

In [618]:
# 4x5 array of random floats between 0-100
np.random.rand(2,3)*100

array([[ 62.71524072,  50.34171661,  52.50635392],
       [ 94.13985141,  64.00819412,  80.38688952]])

In [619]:
# 2x3 array with random ints between 0-4
np.random.randint(100,size=(2,3))

array([[99, 16, 55],
       [37,  8, 24]])

In [620]:
# Basic Operations-

In [621]:
arr6 = np.array([1,2,3,8,9])
arr6

array([1, 2, 3, 8, 9])

In [622]:
arr6+1

array([ 2,  3,  4,  9, 10])

In [623]:
arr6-2

array([-1,  0,  1,  6,  7])

In [624]:
arr6**2

array([ 1,  4,  9, 64, 81])

In [625]:
arr6*10

array([10, 20, 30, 80, 90])

In [626]:
# Inspecting Properties-
A = np.array([[1,8,15],[14,4185,4]])

In [627]:
# No. of elements
A.size

6

In [628]:
# dimension of array
A.shape

(2, 3)

In [629]:
A.dtype

dtype('int32')

In [630]:
# Indexing/ Slicing/ Subsetting-

In [631]:
# Indexing-

In [632]:
# for 1-d arrays-

In [633]:
 B = np.array([1,2,3,4,5,6,7])

In [634]:
B[0]

1

In [635]:
B[-1]

7

In [636]:
B[5]

6

In [637]:
B[1]

2

In [638]:
# Indexes are specified inside the np.array method. 
B[np.array([1,-1,2,4])]

array([2, 7, 3, 5])

In [639]:
# Updating elements in array-
B[1] = 8888

In [640]:
B

array([   1, 8888,    3,    4,    5,    6,    7])

In [641]:
B[[1,5,-1]] = [999,999,999]

In [642]:
B

array([  1, 999,   3,   4,   5, 999, 999])

In [643]:
# for 2-d arrays-

In [644]:
C = np.array([[1,6,8],[5,47,9]])

In [645]:
C

array([[ 1,  6,  8],
       [ 5, 47,  9]])

In [646]:
# Elements at indices
C[[0,0,1,1],[0,1,2,1]]

array([ 1,  6,  9, 47])

In [647]:
C[1,2]

9

In [648]:
C[1]

array([ 5, 47,  9])

In [649]:
C[0]

array([1, 6, 8])

In [650]:
C

array([[ 1,  6,  8],
       [ 5, 47,  9]])

In [651]:
C[1,2] = 999

In [652]:
C

array([[  1,   6,   8],
       [  5,  47, 999]])

In [653]:
# updating elements at (1,0) & (0,2)
C[[1,0],[0,2]]=[111,111]

In [654]:
C

array([[  1,   6, 111],
       [111,  47, 999]])

In [655]:
# Slicing-

In [656]:
# 1-d array-

In [657]:
# array[start:stop:step] -
D = np.arange(1,21)

In [658]:
D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [659]:
D[1:4]

array([2, 3, 4])

In [660]:
# Step of 2
D[0:7:2]

array([1, 3, 5, 7])

In [661]:
D[np.array([3,1,2,-1])]

array([ 4,  2,  3, 20])

In [662]:
D[::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [663]:
D[:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [664]:
D[8:]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [665]:
# 2d array-

In [666]:
F = np.array([[0, 1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10, 11],
              [12, 13, 14, 15, 16, 17],
              [18, 19, 20, 21, 22, 23],
              [24, 25, 26, 27, 28, 29],
              [30, 31, 32, 33, 34, 35]])

In [667]:
F

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [668]:
# All rows & columns-
F[:,:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [669]:
# [row,column]
F[0,1]

1

In [670]:
# [[row],[column]]
# Indices at (0,0),(5,4),(4,3),(1,0),(2,2)
F[[0,5,4,1,2],[0,4,3,0,2]]

array([ 0, 34, 27,  6, 14])

In [671]:
# Slicing
# 0th row & column indexing-3:5
F[0,3:5]

array([3, 4])

In [672]:
F[4:,4:]

array([[28, 29],
       [34, 35]])

In [673]:
# All rows(:) & 2nd column
F[:,2]

array([ 2,  8, 14, 20, 26, 32])

In [674]:
F[2::2,::2]

array([[12, 14, 16],
       [24, 26, 28]])

In [675]:
# Array with first 2 rows and alternate columns(0 and 2)
F[:2,::2]

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [676]:
# Boolean Array Indexing-

In [677]:
z = np.arange(0,15)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [678]:
z[z>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [679]:
z>2

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True], dtype=bool)

In [680]:
y = np.arange(10,101,10)
y

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [681]:
# elements which are divisible by 40-
y[y%40 == 0]

array([40, 80])

In [682]:
# squares of elements which are divisible by 40-
y[y%40 == 0]**2

array([1600, 6400])

In [683]:
mat = np.array([[1,8],[2,8],[5,5],[9,1],[5,6]])
mat

array([[1, 8],
       [2, 8],
       [5, 5],
       [9, 1],
       [5, 6]])

In [684]:
# column sum
mat.sum(0)

array([22, 28])

In [685]:
# row sum
mat.sum(1)

array([ 9, 10, 10, 10, 11])

In [686]:
rowsum = mat.sum(1)
rowsum

array([ 9, 10, 10, 10, 11])

In [687]:
rowsum[rowsum%10 == 0]

array([10, 10, 10])

In [688]:
mat[rowsum%10 == 0]

array([[2, 8],
       [5, 5],
       [9, 1]])

In [689]:
# Sorting/ Resahping-

In [690]:
# Reshaping

In [691]:
n1 = np.arange(0,18)
n1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [692]:
# dimension = 18 (18*1)(1*18)(3*6)(6*3)
n1.shape

(18,)

In [693]:
n1.reshape(3,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [694]:
n1.reshape(6,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [695]:
# Sorting-

In [696]:
n2 = np.random.randint(50,size = (3,4))
n2

array([[20, 33, 19, 11],
       [ 5, 18, 45, 20],
       [11, 32, 33,  5]])

In [697]:
n2.sort()

In [698]:
n2

array([[11, 19, 20, 33],
       [ 5, 18, 20, 45],
       [ 5, 11, 32, 33]])

In [699]:
n3 = np.random.randint(50,size=(5,5))
n3

array([[44, 43, 21, 43, 25],
       [23, 43,  4, 13,  4],
       [22,  0, 41, 13, 26],
       [ 1, 35, 37, 11, 28],
       [ 4, 19, 37, 18,  2]])

In [700]:
# sorted row wise-
n3.sort(axis = 1)

In [701]:
n3

array([[21, 25, 43, 43, 44],
       [ 4,  4, 13, 23, 43],
       [ 0, 13, 22, 26, 41],
       [ 1, 11, 28, 35, 37],
       [ 2,  4, 18, 19, 37]])

In [702]:
n4 = np.random.randint(100,size = (4,5))
n4

array([[58, 81, 64,  5, 62],
       [ 9, 40, 27, 18, 31],
       [59,  4, 99, 90, 90],
       [90, 47, 64, 80, 23]])

In [703]:
# sorted column wise-
n4.sort(axis = 0)

In [704]:
n4

array([[ 9,  4, 27,  5, 23],
       [58, 40, 64, 18, 31],
       [59, 47, 64, 80, 62],
       [90, 81, 99, 90, 90]])

In [705]:
# Numpy | Linear Algebra- (linalg module)
# The Linear Algebra module of NumPy offers various methods to apply linear algebra on any numpy array such as-
# Trace, Determinant, Inverse

In [706]:
n5 = np.random.randint(50,size=(4,4))
n5

array([[ 0,  5, 42, 29],
       [49, 31,  1, 45],
       [18, 14, 30, 43],
       [31, 21, 30, 46]])

In [707]:
# Trace(Sum of diagonal elements)-
np.trace(n5)

107

In [708]:
# Determinant(Suare matrix)-
np.linalg.det(n5)

31246.999999999964

In [709]:
# Inverse-
np.linalg.inv(n5)

array([[-0.20485167, -0.16763209, -0.01155311,  0.30393318],
       [ 0.40435882,  0.31683042, -0.18091337, -0.39574999],
       [ 0.01420936, -0.02883477, -0.07434314,  0.08874452],
       [-0.05581336, -0.01286524,  0.13886133, -0.06029379]])

In [710]:
np.linalg.inv([[1,2],[3,4]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [711]:
# Matrix Multipication-

In [712]:
ha1 = np.array([[1,0,1],[0,1,2]])
ha1

array([[1, 0, 1],
       [0, 1, 2]])

In [713]:
ha2 = np.array([[3,5],[-1,0],[2,-1]])
ha2

array([[ 3,  5],
       [-1,  0],
       [ 2, -1]])

In [714]:
ha1.dot(ha2)

array([[ 5,  4],
       [ 3, -2]])

In [715]:
np.matmul(ha1,ha2)

array([[ 5,  4],
       [ 3, -2]])

In [716]:
np.dot(ha1,ha2)

array([[ 5,  4],
       [ 3, -2]])

In [717]:
# Numpy | Mathematical Function-

In [718]:
# sin functionn-
import numpy as np
import math

in_arr = np.array([0, math.pi, np.pi, np.pi/2, np.pi/4, np.pi/6, np.pi/3])
in_arr

array([ 0.        ,  3.14159265,  3.14159265,  1.57079633,  0.78539816,
        0.52359878,  1.04719755])

In [719]:
sin_values = np.sin(in_arr)
sin_values

array([  0.00000000e+00,   1.22464680e-16,   1.22464680e-16,
         1.00000000e+00,   7.07106781e-01,   5.00000000e-01,
         8.66025404e-01])

In [720]:
np.pi

3.141592653589793

In [721]:
import math
math.pi

3.141592653589793

In [722]:
# Round Off an array-
# np.round(arr)
in1 = [.5, 1.5, 2.5, 3.5, 4.5, 10.1]
in1

[0.5, 1.5, 2.5, 3.5, 4.5, 10.1]

In [723]:
round_off_values = np.round_(in1)

In [724]:
round_off_values

array([  0.,   2.,   2.,   4.,   4.,  10.])

In [725]:
# Exponents and logarithms Functions– 
# np.exp(arr)
# np.log(arr)   
# np.log10(arr) - Return the base 10 logarithm of the input array, element-wise.
# np.log2(arr) - Calculate 2**p for all p in the input array.
## Natural logarithm log is the inverse of the exp(), so that log(exp(x)) = x. The natural logarithm is log in base e.

In [726]:
in2 = np.arange(0,5,dtype = int)
in2

array([0, 1, 2, 3, 4])

In [727]:
exp_arr = np.exp(in2)
exp_arr

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

In [728]:
in3 = np.random.randint(1,10,size = (1,5))
in3

array([[9, 2, 3, 4, 1]])

In [729]:
loge_arr = np.log(in3)
loge_arr

array([[ 2.19722458,  0.69314718,  1.09861229,  1.38629436,  0.        ]])

In [730]:
in4 = np.random.randint(1,10,size=(1,4))
in4

array([[1, 5, 7, 8]])

In [731]:
log10_arr = np.log10(in4)
log10_arr

array([[ 0.        ,  0.69897   ,  0.84509804,  0.90308999]])

In [732]:
# Arithmatic Function-

In [733]:
# Reciprocal function-
# np.reciprocal(array)
# NOTE-For integer arguments with absolute value larger than 1, the result is always zero because of the way Python handles integer division. 
# For integer zero the result is an overflow.

In [734]:
in5 = np.random.rand(1,5)*100
in5

array([[ 54.31361831,  74.43398686,   2.7496865 ,  38.09264226,
         77.88761432]])

In [735]:
np.reciprocal(in5)

array([[ 0.01841159,  0.01343472,  0.36367782,  0.02625179,  0.01283901]])

In [736]:
in6 = np.random.randint(1,100,size=(1,6))
in6

array([[46, 67, 54, 96, 36, 57]])

In [737]:
np.reciprocal(in6)

array([[0, 0, 0, 0, 0, 0]], dtype=int32)

In [738]:
a1 = np.array([1,5,8,9])

In [739]:
a2 = np.array([7,8,2,4])

In [740]:
# np.add()- element wise
np.add(a1,a2)

array([ 8, 13, 10, 13])

In [741]:
# np.divide()- element wise division
np.divide(a1,a2)

array([ 0.14285714,  0.625     ,  4.        ,  2.25      ])

In [742]:
# np.multiply()- element wisee
np.multiply(a1,a2)

array([ 7, 40, 16, 36])

In [743]:
# np.subtract()- element wise
np.subtract(a1,a2)

array([-6, -3,  6,  5])

In [744]:
# np.power()- First array elements raised to powers from second array, element-wise.
np.power(a1,a2)

array([     1, 390625,     64,   6561], dtype=int32)

In [745]:
# np.negative()- Numerical negative, element-wise
np.negative(a1)

array([-1, -5, -8, -9])

In [746]:
# cbrt function - np.cbrt(array) cube root
np.cbrt(np.array([1,27000,64,-1000]))

array([  1.,  30.,   4., -10.])

In [747]:
# sqrt function- np.sqrt(array)
np.sqrt(np.array([16,9,225]))

array([  4.,   3.,  15.])

In [748]:
np.max(a1)

9

In [749]:
np.min(a1)

1

In [750]:
# Array Flatten- np.flatten(array)
aaa = np.array([a1,a2])
type(aaa)

numpy.ndarray

In [751]:
a1

array([1, 5, 8, 9])

In [752]:
a2

array([7, 8, 2, 4])

In [753]:
aaa.flatten()

array([1, 5, 8, 9, 7, 8, 2, 4])

In [754]:
# Matrix multiplication and Array multiplication-
a = np.array([[1, 2], 
            [3, 4]]) 
b = np.array([[4, 3], 
            [2, 1]])

In [755]:
# or a.dot(b)
np.dot(a,b)

array([[ 8,  5],
       [20, 13]])

In [756]:
a*b

array([[4, 6],
       [6, 4]])

In [757]:
# Transpse of a Matrix-   matrix.T
mtx = np.random.randint(1,50,size = (3,4))
mtx

array([[30, 31, 24, 43],
       [36, 48, 46, 27],
       [14, 22, 34, 47]])

In [758]:
mtx.T

array([[30, 36, 14],
       [31, 48, 22],
       [24, 46, 34],
       [43, 27, 47]])