In [19]:
# Numpy Basics-

In [20]:
#                Why do we need NumPy ? 
# A question arises that why do we need NumPy when python lists are already there. 
# The answer to it is we cannot perform operations on all the elements of two list directly. 
# For example we cannot multiply two lists directly we will have to do it element wise.
# This is where the role of NumPy comes into play.

In [21]:
# Array Creation-
# Array creation using numpy methods -
import numpy as np
arr1 = np.array([1,8,11])
arr1

array([ 1,  8, 11])

In [22]:
arr2 = np.array([[1,5,88],[1,4,99]])
arr2

array([[ 1,  5, 88],
       [ 1,  4, 99]])

In [23]:
arr3 = np.array((1,2,3,8))
arr3

array([1, 2, 3, 8])

In [24]:
type(arr3)

numpy.ndarray

In [25]:
arr4 = np.ones(3)
arr4

array([ 1.,  1.,  1.])

In [26]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [27]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [28]:
arr5 = np.array([[1,5,9],[4,88,10]],dtype=int)
arr5


array([[ 1,  5,  9],
       [ 4, 88, 10]])

In [29]:
# defining datatype-
np.array([[1,8,9],[5,8,4]],dtype = float)

array([[ 1.,  8.,  9.],
       [ 5.,  8.,  4.]])

In [30]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [31]:
# returns identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [32]:
# returns evenly spaced values within a given interval. step size is specified
np.arange(1,16,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [33]:
# returns evenly spaced values within a given interval. num no. of elements are returned.
np.linspace(1,16,4)

array([  1.,   6.,  11.,  16.])

In [34]:
np.arange(1,16,4)

array([ 1,  5,  9, 13])

In [35]:
# 2x4 array of all values of 8
np.full((2,4),8,dtype = int)

array([[8, 8, 8, 8],
       [8, 8, 8, 8]])

In [36]:
#4x5 array of random floats between 0-1
np.random.rand(2,3)

array([[ 0.76351183,  0.91481997,  0.31834029],
       [ 0.26745218,  0.6080098 ,  0.61425909]])

In [37]:
# 4x5 array of random floats between 0-100
np.random.rand(2,3)*100

array([[ 48.7868233 ,  26.69013026,  53.61939805],
       [ 35.00852789,  86.61365368,  95.464631  ]])

In [38]:
# 2x3 array with random ints between 0-4
np.random.randint(100,size=(2,3))

array([[92, 41, 12],
       [ 4, 14, 53]])

In [39]:
# Basic Operations-

In [40]:
arr6 = np.array([1,2,3,8,9])
arr6

array([1, 2, 3, 8, 9])

In [41]:
arr6+1

array([ 2,  3,  4,  9, 10])

In [42]:
arr6-2

array([-1,  0,  1,  6,  7])

In [43]:
arr6**2

array([ 1,  4,  9, 64, 81])

In [44]:
arr6*10

array([10, 20, 30, 80, 90])

In [45]:
# Inspecting Properties-
A = np.array([[1,8,15],[14,4185,4]])

In [46]:
# No. of elements
A.size

6

In [47]:
# dimension of array
A.shape

(2, 3)

In [48]:
A.dtype

dtype('int32')

In [49]:
# Indexing/ Slicing/ Subsetting-

In [50]:
# Indexing-

In [51]:
# for 1-d arrays-

In [52]:
 B = np.array([1,2,3,4,5,6,7])

In [53]:
B[0]

1

In [54]:
B[-1]

7

In [55]:
B[5]

6

In [56]:
B[1]

2

In [57]:
# Indexes are specified inside the np.array method. 
B[np.array([1,-1,2,4])]

array([2, 7, 3, 5])

In [58]:
# Updating elements in array-
B[1] = 8888

In [59]:
B

array([   1, 8888,    3,    4,    5,    6,    7])

In [60]:
B[[1,5,-1]] = [999,999,999]

In [61]:
B

array([  1, 999,   3,   4,   5, 999, 999])

In [62]:
# for 2-d arrays-

In [63]:
C = np.array([[1,6,8],[5,47,9]])

In [64]:
C

array([[ 1,  6,  8],
       [ 5, 47,  9]])

In [65]:
# Elements at indices
C[[0,0,1,1],[0,1,2,1]]

array([ 1,  6,  9, 47])

In [66]:
C[1,2]

9

In [67]:
C[1]

array([ 5, 47,  9])

In [68]:
C[0]

array([1, 6, 8])

In [69]:
C

array([[ 1,  6,  8],
       [ 5, 47,  9]])

In [70]:
C[1,2] = 999

In [71]:
C

array([[  1,   6,   8],
       [  5,  47, 999]])

In [72]:
# updating elements at (1,0) & (0,2)
C[[1,0],[0,2]]=[111,111]

In [73]:
C

array([[  1,   6, 111],
       [111,  47, 999]])

In [74]:
# Slicing-

In [75]:
# 1-d array-

In [76]:
# array[start:stop:step] -
D = np.arange(1,21)

In [77]:
D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [78]:
D[1:4]

array([2, 3, 4])

In [79]:
# Step of 2
D[0:7:2]

array([1, 3, 5, 7])

In [80]:
D[np.array([3,1,2,-1])]

array([ 4,  2,  3, 20])

In [81]:
D[::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [82]:
D[:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [83]:
D[8:]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [84]:
# 2d array-

In [85]:
F = np.array([[0, 1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10, 11],
              [12, 13, 14, 15, 16, 17],
              [18, 19, 20, 21, 22, 23],
              [24, 25, 26, 27, 28, 29],
              [30, 31, 32, 33, 34, 35]])

In [86]:
F

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [87]:
# All rows & columns-
F[:,:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [88]:
# [row,column]
F[0,1]

1

In [89]:
# [[row],[column]]
# Indices at (0,0),(5,4),(4,3),(1,0),(2,2)
F[[0,5,4,1,2],[0,4,3,0,2]]

array([ 0, 34, 27,  6, 14])

In [90]:
# Slicing
# 0th row & column indexing-3:5
F[0,3:5]

array([3, 4])

In [91]:
F[4:,4:]

array([[28, 29],
       [34, 35]])

In [92]:
# All rows(:) & 2nd column
F[:,2]

array([ 2,  8, 14, 20, 26, 32])

In [93]:
F[2::2,::2]

array([[12, 14, 16],
       [24, 26, 28]])

In [94]:
# Array with first 2 rows and alternate columns(0 and 2)
F[:2,::2]

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [95]:
# Boolean Array Indexing-

In [96]:
z = np.arange(0,15)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [97]:
z[z>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [98]:
z>2

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True], dtype=bool)

In [99]:
y = np.arange(10,101,10)
y

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [100]:
# elements which are divisible by 40-
y[y%40 == 0]

array([40, 80])

In [101]:
# squares of elements which are divisible by 40-
y[y%40 == 0]**2

array([1600, 6400])

In [102]:
mat = np.array([[1,8],[2,8],[5,5],[9,1],[5,6]])
mat

array([[1, 8],
       [2, 8],
       [5, 5],
       [9, 1],
       [5, 6]])

In [103]:
# column sum
mat.sum(0)

array([22, 28])

In [104]:
# row sum
mat.sum(1)

array([ 9, 10, 10, 10, 11])

In [105]:
rowsum = mat.sum(1)
rowsum

array([ 9, 10, 10, 10, 11])

In [106]:
rowsum[rowsum%10 == 0]

array([10, 10, 10])

In [107]:
mat[rowsum%10 == 0]

array([[2, 8],
       [5, 5],
       [9, 1]])

In [108]:
# Sorting/ Resahping-

In [109]:
# Reshaping

In [110]:
n1 = np.arange(0,18)
n1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [111]:
# dimension = 18 (18*1)(1*18)(3*6)(6*3)
n1.shape

(18,)

In [112]:
n1.reshape(3,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [113]:
n1.reshape(6,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [114]:
# Sorting-

In [115]:
n2 = np.random.randint(50,size = (3,4))
n2

array([[34,  8, 25, 25],
       [15, 14,  4,  9],
       [42,  1, 33, 10]])

In [116]:
n2.sort()

In [117]:
n2

array([[ 8, 25, 25, 34],
       [ 4,  9, 14, 15],
       [ 1, 10, 33, 42]])

In [118]:
n3 = np.random.randint(50,size=(5,5))
n3

array([[ 0, 45, 31, 31, 27],
       [44,  9,  2, 31, 37],
       [12, 47,  6,  5,  6],
       [11, 41, 39, 13,  1],
       [39,  4, 37, 37, 49]])

In [119]:
# sorted row wise-
n3.sort(axis = 1)

In [120]:
n3

array([[ 0, 27, 31, 31, 45],
       [ 2,  9, 31, 37, 44],
       [ 5,  6,  6, 12, 47],
       [ 1, 11, 13, 39, 41],
       [ 4, 37, 37, 39, 49]])

In [121]:
n4 = np.random.randint(100,size = (4,5))
n4

array([[ 8, 89, 24, 69, 85],
       [91, 90, 79, 81, 25],
       [16, 90, 12, 18, 71],
       [55, 98, 93, 86, 97]])

In [122]:
# sorted column wise-
n4.sort(axis = 0)

In [123]:
n4

array([[ 8, 89, 12, 18, 25],
       [16, 90, 24, 69, 71],
       [55, 90, 79, 81, 85],
       [91, 98, 93, 86, 97]])

In [124]:
# Numpy | Linear Algebra- (linalg module)
# The Linear Algebra module of NumPy offers various methods to apply linear algebra on any numpy array such as-
# Trace, Determinant, Inverse

In [125]:
n5 = np.random.randint(50,size=(4,4))
n5

array([[ 2, 11, 32, 10],
       [ 2, 48, 29, 40],
       [14, 49, 10, 23],
       [31,  1, 11, 28]])

In [126]:
# Trace(Sum of diagonal elements)-
np.trace(n5)

88

In [127]:
# Determinant(Suare matrix)-
np.linalg.det(n5)

-1063700.9999999998

In [128]:
# Inverse-
np.linalg.inv(n5)

array([[ 0.015667  , -0.03533042,  0.03069096,  0.01966624],
       [ 0.00293598, -0.00824104,  0.02807368, -0.01233617],
       [ 0.03957315, -0.00829274, -0.00072577, -0.00169032],
       [-0.03299705,  0.04266801, -0.03469678,  0.01504558]])

In [129]:
np.linalg.inv([[1,2],[3,4]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [130]:
# Matrix Multipication-

In [131]:
ha1 = np.array([[1,0,1],[0,1,2]])
ha1

array([[1, 0, 1],
       [0, 1, 2]])

In [132]:
ha2 = np.array([[3,5],[-1,0],[2,-1]])
ha2

array([[ 3,  5],
       [-1,  0],
       [ 2, -1]])

In [133]:
ha1.dot(ha2)

array([[ 5,  4],
       [ 3, -2]])

In [134]:
np.matmul(ha1,ha2)

array([[ 5,  4],
       [ 3, -2]])

In [135]:
np.dot(ha1,ha2)

array([[ 5,  4],
       [ 3, -2]])

In [136]:
# Numpy | Mathematical Function-

In [137]:
# sin functionn-
import numpy as np
import math

in_arr = np.array([0, math.pi, np.pi, np.pi/2, np.pi/4, np.pi/6, np.pi/3])
in_arr

array([ 0.        ,  3.14159265,  3.14159265,  1.57079633,  0.78539816,
        0.52359878,  1.04719755])

In [138]:
sin_values = np.sin(in_arr)
sin_values

array([  0.00000000e+00,   1.22464680e-16,   1.22464680e-16,
         1.00000000e+00,   7.07106781e-01,   5.00000000e-01,
         8.66025404e-01])

In [139]:
np.pi

3.141592653589793

In [140]:
import math
math.pi

3.141592653589793

In [141]:
# Round Off an array-
# np.round(arr)
in1 = [.5, 1.5, 2.5, 3.5, 4.5, 10.1]
in1

[0.5, 1.5, 2.5, 3.5, 4.5, 10.1]

In [142]:
round_off_values = np.round_(in1)

In [143]:
round_off_values

array([  0.,   2.,   2.,   4.,   4.,  10.])

In [144]:
# Exponents and logarithms Functions– 
# np.exp(arr)
# np.log(arr)   
# np.log10(arr) - Return the base 10 logarithm of the input array, element-wise.
# np.log2(arr) - Calculate 2**p for all p in the input array.
## Natural logarithm log is the inverse of the exp(), so that log(exp(x)) = x. The natural logarithm is log in base e.

In [145]:
in2 = np.arange(0,5,dtype = int)
in2

array([0, 1, 2, 3, 4])

In [146]:
exp_arr = np.exp(in2)
exp_arr

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

In [147]:
in3 = np.random.randint(1,10,size = (1,5))
in3

array([[4, 1, 4, 1, 9]])

In [148]:
loge_arr = np.log(in3)
loge_arr

array([[ 1.38629436,  0.        ,  1.38629436,  0.        ,  2.19722458]])

In [149]:
in4 = np.random.randint(1,10,size=(1,4))
in4

array([[4, 9, 3, 3]])

In [150]:
log10_arr = np.log10(in4)
log10_arr

array([[ 0.60205999,  0.95424251,  0.47712125,  0.47712125]])

In [151]:
# Arithmatic Function-

In [152]:
# Reciprocal function-
# np.reciprocal(array)
# NOTE-For integer arguments with absolute value larger than 1, the result is always zero because of the way Python handles integer division. 
# For integer zero the result is an overflow.

In [153]:
in5 = np.random.rand(1,5)*100
in5

array([[ 62.34016354,  32.77498272,  92.77271316,  35.71572185,
         69.10648368]])

In [154]:
np.reciprocal(in5)

array([[ 0.01604102,  0.03051108,  0.01077903,  0.02799887,  0.01447042]])

In [155]:
in6 = np.random.randint(1,100,size=(1,6))
in6

array([[47, 20, 95, 79, 28,  2]])

In [156]:
np.reciprocal(in6)

array([[0, 0, 0, 0, 0, 0]], dtype=int32)

In [157]:
a1 = np.array([1,5,8,9])

In [158]:
a2 = np.array([7,8,2,4])

In [159]:
# np.add()- element wise
np.add(a1,a2)

array([ 8, 13, 10, 13])

In [160]:
# np.divide()- element wise division
np.divide(a1,a2)

array([ 0.14285714,  0.625     ,  4.        ,  2.25      ])

In [161]:
# np.multiply()- element wisee
np.multiply(a1,a2)

array([ 7, 40, 16, 36])

In [162]:
# np.subtract()- element wise
np.subtract(a1,a2)

array([-6, -3,  6,  5])

In [163]:
# np.power()- First array elements raised to powers from second array, element-wise.
np.power(a1,a2)

array([     1, 390625,     64,   6561], dtype=int32)

In [164]:
# np.negative()- Numerical negative, element-wise
np.negative(a1)

array([-1, -5, -8, -9])

In [165]:
# cbrt function - np.cbrt(array) cube root
np.cbrt(np.array([1,27000,64,-1000]))

array([  1.,  30.,   4., -10.])

In [166]:
# sqrt function- np.sqrt(array)
np.sqrt(np.array([16,9,225]))

array([  4.,   3.,  15.])

In [167]:
np.max(a1)

9

In [168]:
np.min(a1)

1

In [169]:
# Array Flatten- np.flatten(array)
aaa = np.array([a1,a2])
type(aaa)

numpy.ndarray

In [170]:
a1

array([1, 5, 8, 9])

In [171]:
a2

array([7, 8, 2, 4])

In [172]:
aaa.flatten()

array([1, 5, 8, 9, 7, 8, 2, 4])

In [173]:
# Matrix multiplication and Array multiplication-
a = np.array([[1, 2], 
            [3, 4]]) 
b = np.array([[4, 3], 
            [2, 1]])

In [174]:
# or a.dot(b)
np.dot(a,b)

array([[ 8,  5],
       [20, 13]])

In [175]:
a*b

array([[4, 6],
       [6, 4]])

In [176]:
# Transpse of a Matrix-   matrix.T
mtx = np.random.randint(1,50,size = (3,4))
mtx

array([[10, 15, 10, 17],
       [ 8, 29, 11, 24],
       [ 6,  6, 36, 19]])

In [177]:
mtx.T

array([[10,  8,  6],
       [15, 29,  6],
       [10, 11, 36],
       [17, 24, 19]])

In [178]:
# Matrix
mtx = np.array([[1,2],[3,4]])
mtx

array([[1, 2],
       [3, 4]])

In [179]:
# Array
arr = np.array([5,6])
arr

array([5, 6])

In [180]:
mtx.shape

(2, 2)

In [181]:
arr.shape

(2,)

In [182]:
# Numpy matrix append array as row

In [183]:
# make it 2d instead of 1d
arr = np.array([arr])
arr

array([[5, 6]])

In [184]:
arr.shape

(1, 2)

In [185]:
np.append(mtx,arr,axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [186]:
# Numpy matrix append array as column

In [187]:
# it has already been converted into 2d (above)
arr

array([[5, 6]])

In [188]:
mtx

array([[1, 2],
       [3, 4]])

In [189]:
np.append(mtx, arr.T, axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [190]:
ins = np.array([[0],[0]])
ins

array([[0],
       [0]])

In [191]:
ins.shape

(2, 1)